### PR TITLE
Fix systemd example for configuring nginx_exporter.service

### PR DESCRIPTION
**Pull request by bruno-espino**
when implementing nginx exporter, I used the example under `examples/systemd` but I was not seeing my nginx stub metrics.
When enabling journal logging for the service and checking with `systemctl status nginx_exporter -l` I could see the `nginx.scrape-uri` was not being parsed correctly. Hence why I couldn't see my stub metrics.
After removing both `""` I was able to see my metrics

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/main/CONTRIBUTING.md)
  guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have ensured the README is up to date
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch on my own fork

### CODE REVIEW

**Review by lucacome — APPROVED** [review]
Hi @bruno-espino thanks for opening the PR!

Just out of curiosity, which OS/version are you using? I tried this on Ubuntu 23.10 and it's not complaining about the quotes, it's just stripping them out...

**Comment by brunococinoJC** [comment]
> Hi @bruno-espino thanks for opening the PR!
> Just out of curiosity, which OS/version are you using? I tried this on Ubuntu 23.10 and it's not complaining about the quotes, it's just stripping them out...

Hey @lucacome! 
I faced this issue on Amazon Linux 2, with systemd version 219

**Comment by jjngx** [comment]
Hi @brunococinoJC , I will be testing it tomorrow.

**Review by jjngx — APPROVED** [review]

**Comment by jjngx** [comment]
@brunococinoJC thanks for contributing

**Pull request merged**
