### PR TITLE
Add GitHub Action workflow for F5 CLA integration

### PR DESCRIPTION
**Pull request by TasoOneAsia**
### Proposed changes

An updated version of #661 that includes a GitHub action workflow integrating the F5 CLA into the typical GitHub pull-request flow for individual contributors.

As part of this workflow's configuration, the following usernames were marked as F5 maintainers:

* `lucacome`
* `pleshakov` 

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/main/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have ensured the README is up to date
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch on my own fork

### CODE REVIEW

**Review by vepatel — APPROVED** [review]

**Comment by lucacome** [comment]
I don't know if @pleshakov still wants to be a maintainer

**Comment by TasoOneAsia** [comment]
@lucacome I can remove him from this changeset if desired. However, there isn't much of a net-negative to being listed, all it does is prevents the bot from being implicitly triggered to prompt for a CLA upon a PR to `main`. 

In an ideal world, the maintainer allowlist would be defined at the organization level instead of per-project, but our chosen solution does not have that functionality for the timebeing.

**Comment by lucacome** [comment]
@TasoOneAsia sounds good to me to leave him there.

Is this ready to be merged?

**Comment by TasoOneAsia** [comment]
@lucacome yup, all set on my side 👍

**Pull request merged**
