### PR TITLE
feat: support metric: http_request_time_total

### PR DESCRIPTION
**Pull request by theharveyz**
### Proposed changes
Add metric: http_request_time_total

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/master/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have ensured the README is up to date
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

### CODE REVIEW

**Comment by pleshakov** [comment]
Hi @theharveyz 

Thanks for the PR!

Could you possibly clarify a few details about this PR?

As the `stub_status` doesn't expose the request_time metric, how do you generate the correct stub_status page on NGINX?
What does this metric represent?

**Comment by theharveyz** [comment]
@pleshakov  Thanks for your comment. This PR is for compatibility with [Tengine](https://github.com/alibaba/tengine). 

The total requests' response time, which is in millisecond, is also recorded in the Tengine.
So you can calculate the mean response time. Here is an example of the output of stub_status:
```
Active connections: 1
server accepts handled requests request_time
1140 1140 1140 75806
Reading: 0 Writing: 1 Waiting: 0
```

**Comment by pleshakov** [comment]
@theharveyz 
Apologies for the delay!

We would like to keep this project focused only on the standard versions of NGINX (and NGINX Plus), without supporting custom NGINX versions or any third-party modules.

Thanks for sending a PR. However, we will not accept it.

**Comment by theharveyz** [comment]
@pleshakov  Sorry to bother you. I will close this PR.

**Pull request closed without merging**
