### PR TITLE
Fix wrong exit status (#393)

### PR DESCRIPTION
**Pull request by n-rodriguez**
### Proposed changes

Fix exit status when closing app.

Taken from : https://clavinjune.dev/en/blogs/golang-http-server-graceful-shutdown/

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/main/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have ensured the README is up to date
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch on my own fork

### CODE REVIEW

**Comment by n-rodriguez** [comment]
It now works as expected :

```sh
nicolas@MBP-de-Nicolas:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter$ ./nginx-prometheus-exporter -nginx.scrape-uri http://localhost:9090/nginx-status
NGINX Prometheus Exporter version=0.11.0 commit=d2b813e79edbdd89a8f318be4d7ef7ebbd9c5707 date=2023-04-18T23:49:43Z, dirty=true, arch=darwin/amd64, go=go1.20.2
2023/04/23 22:34:48 Starting...
2023/04/23 22:34:48 Listening on :9113
2023/04/23 22:34:48 NGINX Prometheus Exporter has successfully started
^C2023/04/23 22:34:49 Signal received: 'interrupt'. Exiting...
2023/04/23 22:34:49 Graceful shutdown complete.
nicolas@MBP-de-Nicolas:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter$ echo $?
0
```

**Comment by n-rodriguez** [comment]
ping @lucacome

**Review by jjngx — APPROVED** [review]

**Comment by n-rodriguez** [comment]
Hi there! Is there anything to do to get this PR merged? Thank you!

**Comment by n-rodriguez** [comment]
ping @jjngx

**Comment by n-rodriguez** [comment]
I've just rebased, still ok :

```sh
nicolas@cloud.thetuxhouse.org:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter ./nginx-prometheus-exporter --nginx.scrape-uri='http://127.0.0.1:9000/nginx-status'
ts=2023-06-11T16:05:33.174Z caller=exporter.go:178 level=info msg="Starting nginx-prometheus-exporter" version="(version=, branch=, revision=3957b7fdc7ffd2723b26f976bb801b5cb7dd6982)"
ts=2023-06-11T16:05:33.174Z caller=exporter.go:179 level=info msg="Build context" build_context="(go=go1.20.3, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2023-06-11T16:05:33.176Z caller=exporter.go:281 level=info msg="Listening on address" address=:9113
ts=2023-06-11T16:05:33.177Z caller=exporter.go:115 level=info msg="NGINX Prometheus Exporter has successfully started"
^Cts=2023-06-11T16:05:34.163Z caller=exporter.go:307 level=info msg="Signal received" signal=interrupt
ts=2023-06-11T16:05:34.163Z caller=exporter.go:130 level=info msg="Graceful shutdown complete."
nicolas@cloud.thetuxhouse.org:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter echo $?
0
```

**Comment by n-rodriguez** [comment]
I've just rebase, still ok :

```sh
nicolas@cloud:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter ./nginx-prometheus-exporter --nginx.scrape-uri='http://127.0.0.1:9000/nginx-status'
ts=2023-06-11T16:05:33.174Z caller=exporter.go:178 level=info msg="Starting nginx-prometheus-exporter" version="(version=, branch=, revision=3957b7fdc7ffd2723b26f976bb801b5cb7dd6982)"
ts=2023-06-11T16:05:33.174Z caller=exporter.go:179 level=info msg="Build context" build_context="(go=go1.20.3, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2023-06-11T16:05:33.176Z caller=exporter.go:281 level=info msg="Listening on address" address=:9113
ts=2023-06-11T16:05:33.177Z caller=exporter.go:115 level=info msg="NGINX Prometheus Exporter has successfully started"
^Cts=2023-06-11T16:05:34.163Z caller=exporter.go:307 level=info msg="Signal received" signal=interrupt
ts=2023-06-11T16:05:34.163Z caller=exporter.go:130 level=info msg="Graceful shutdown complete."
nicolas@cloud:~/go/src/github.com/n-rodriguez/nginx-prometheus-exporter echo $?
0
```

**Comment by n-rodriguez** [comment]
ping @lucacome

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Any news? It would be great to have some news... this PR wasn't generated by chatgpt...

**Comment by n-rodriguez** [comment]
ping @lucacome

**Comment by lucacome** [comment]
Hi @n-rodriguez I've opened https://github.com/nginxinc/nginx-prometheus-exporter/pull/461 that changes how we start the server. I've used `signal.NotifyContext` that was introduced in go 1.16, instead of `signal.Notify`. I think it will fix your issues without adding additional functions. Let me know what you think about it 🙏

**Comment by n-rodriguez** [comment]
Closing it in favour of https://github.com/nginxinc/nginx-prometheus-exporter/pull/461

**Pull request closed without merging**
