### PR TITLE
Nginx Retries intently for 0. Default retry count is 0

### PR DESCRIPTION
**Pull request by Pamir**
### Proposed changes
Default retry mechanism is not suitable for k8s mechanism. Somehow if nginx is not up and running as sidecar, because of nginx-exporter it can stay in crashloopbackoff state.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/master/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes  
      - [x] Check with TryCount 5 / 7 / 10
      - [x] Check with 0 for infinite loop   
- [x] I have ensured the README is up to date
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

### CODE REVIEW

**Comment by lucacome** [comment]
Hi @Pamir thanks for the PR! Would you mind rebasing against master and fixing the linting issues?

**Comment by OptimusKoala** [comment]
Hello @Pamir :)

I used your fork and it solved my crash loop issue.
Thank you :)

Best regards,
Michael.

**Comment by OptimusKoala** [comment]
Hello :)

I tried @Pamir 's fork and I had infinite errors:

`Could not create Nginx Client. Retrying in 5s...
Could not create Nginx Client. Retrying in 5s...
Could not create Nginx Client. Retrying in 5s...
Could not create Nginx Client. Retrying in 5s...
Could not create Nginx Client. Retrying in 5s...` 

Regards,
Michael.

**Comment by Pamir** [comment]
> Hello :)
> 
> I tried @Pamir 's fork and I had infinite errors:
> 
> `Could not create Nginx Client. Retrying in 5s...`
> 
> Regards, Michael.

Hi,
The reason behind it, there is no option to adopt it to kubernetes as a sidecar. Master branch tries with static max count. It tries once or up to max count. I wanted to make it nginx exporter to try infinitely while the sidecar is ready for serving. Once the sidecar is ready it starts to work.

Regards

**Comment by Pamir** [comment]
> Hi @Pamir thanks for the PR! Would you mind rebasing against master and fixing the linting issues?

Definitely do that.

**Comment by OptimusKoala** [comment]
> > Hello :)
> > I tried @Pamir 's fork and I had infinite errors:
> > `Could not create Nginx Client. Retrying in 5s...`
> > Regards, Michael.
> 
> Hi, The reason behind it, there is no option to adopt it to kubernetes as a sidecar. Master branch tries with static max count. It tries once or up to max count. I wanted to make it nginx exporter to try infinitely while the sidecar is ready for serving. Once the sidecar is ready it starts to work.
> 
> Regards

Hi Pamir :) 
Thank you for your answer.
Ok I got it, I just used the "- nginx.retries=10" in my k8s deploy file and it solved my issue. 

Regards, Michael.

**Pull request closed without merging**
